/**
 * @file Camera.h
 * @author orbitchen
 * @brief Different cameras. Need to be investigated.
 * @version 0.1
 * @date 2022-04-30
 *
 * @copyright NJUMeta (c) 2022 
 * www.njumeta.com
 *
 */
#pragma once

#include "CoreLayer/Geometry/Geometry.h"
#include "CoreLayer/Ray/Ray.h"

/// \brief This is used by camera to generate a ray
struct CameraSample {
	Point2d xy;
	double time;
	Point2d lens;
};

/// @defgroup Camera

/**
 * @brief Base class for all camera
 * @ingroup Camera
 */
class Camera
{
public:

	/**
	 * @brief Generate a ray from camera
	 * 
	 * @param filmResolution 	The resolution of the film
	 * @param pixelPosition 	The position of the current pixel
	 * @param sample 			A CameraSample generated by sampler
	 * @return Ray 
	 */
	virtual Ray generateRay(const Point2i &filmResolution, 
							const Point2i &pixelPosition, 
							const CameraSample &sample) const = 0;
};